# Generated by Django 6.0.5 on 2026-05-14 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('estado_operacional', models.CharField(choices=[('Operativo', 'Operativo'), ('En Mantencion', 'En Mantención'), ('FueraServicio', 'Fuera de Servicio')], default='Operativo', max_length=30)),
                ('kilometraje_actual', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.centrocosto')),
            ],
        ),
    ]
