# Generated by Django 6.0.5 on 2026-05-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_remove_vehiculo_estado_operacional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='estado',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado_administrativo',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Dado de Baja', 'Dado de Baja')], default='Vigente', max_length=100),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado_operacional',
            field=models.CharField(choices=[('No informado', 'No informado'), ('Operativo', 'Operativo'), ('En Mantencion', 'En Mantención'), ('FueraServicio', 'Fuera de Servicio')], default='No informado', max_length=100),
        ),
    ]
