# Generated by Django 6.0.5 on 2026-05-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_remove_vehiculo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tarifa_mensual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
