# Generated by Django 6.0.5 on 2026-05-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0005_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='rol_operativo',
        ),
    ]
