# Generated by Django 6.0.5 on 2026-05-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0006_remove_perfilusuario_rol_operativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='subestado_no_operativo',
            field=models.CharField(blank=True, choices=[('Mantencion', 'En mantención'), ('Reparacion', 'En reparación'), ('Detenido', 'Detenido')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_operacional',
            field=models.CharField(choices=[('Operativo', 'Operativo'), ('No operativo', 'No operativo'), ('No informado', 'No informado')], default='No informado', max_length=100),
        ),
    ]
