# Generated by Django 6.0.5 on 2026-05-25 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0007_vehiculo_subestado_no_operativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_texto', models.CharField(blank=True, help_text='Nombre de usuario al momento de la acción.', max_length=150, null=True)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('BAJA', 'Dar de baja'), ('REACTIVAR', 'Reactivar'), ('IMPORTAR', 'Importar datos'), ('RESET_PASSWORD', 'Resetear contraseña'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('OTRO', 'Otro')], max_length=50)),
                ('modulo', models.CharField(help_text='Módulo donde ocurrió la acción. Ej: Vehículos, Usuarios, Importación.', max_length=100)),
                ('modelo_afectado', models.CharField(blank=True, help_text='Modelo afectado. Ej: Vehiculo, User, CentroCosto.', max_length=100, null=True)),
                ('objeto_id', models.CharField(blank=True, help_text='ID del objeto afectado.', max_length=100, null=True)),
                ('objeto_repr', models.CharField(blank=True, help_text='Representación legible del objeto. Ej: QAQA01 - Toyota.', max_length=250, null=True)),
                ('descripcion', models.TextField(help_text='Descripción resumida de la acción realizada.')),
                ('valor_anterior', models.TextField(blank=True, help_text='Valor anterior o resumen previo del dato modificado.', null=True)),
                ('valor_nuevo', models.TextField(blank=True, help_text='Valor nuevo o resumen posterior del dato modificado.', null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de acción',
                'verbose_name_plural': 'Bitácora de acciones',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
