# Generated by Django 6.0.5 on 2026-05-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0008_bitacoraaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='motivo_baja',
            field=models.CharField(blank=True, choices=[('Termino contrato', 'Término de contrato'), ('Venta', 'Venta'), ('Siniestro', 'Siniestro'), ('Reemplazo', 'Reemplazo'), ('Fuera de servicio definitivo', 'Fuera de servicio definitivo'), ('Otro', 'Otro')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='observacion_baja',
            field=models.TextField(blank=True, null=True),
        ),
    ]
