# Generated by Django 6.0.5 on 2026-05-26 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0009_vehiculo_motivo_baja_vehiculo_observacion_baja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBajaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateField()),
                ('motivo_baja', models.CharField(choices=[('Termino contrato', 'Término de contrato'), ('Venta', 'Venta'), ('Siniestro', 'Siniestro'), ('Reemplazo', 'Reemplazo'), ('Fuera de servicio definitivo', 'Fuera de servicio definitivo'), ('Otro', 'Otro')], max_length=100)),
                ('observacion_baja', models.TextField(blank=True, null=True)),
                ('fecha_reactivacion', models.DateField(blank=True, null=True)),
                ('observacion_reactivacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario_baja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_registradas', to=settings.AUTH_USER_MODEL)),
                ('usuario_reactivacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactivaciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_bajas', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Historial de baja de vehículo',
                'verbose_name_plural': 'Historial de bajas de vehículos',
                'ordering': ['-fecha_baja', '-creado_en'],
            },
        ),
    ]
