# Generated by Django 6.0.5 on 2026-05-26 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0010_historialbajavehiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraaccion',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('BAJA', 'Dar de baja'), ('REACTIVAR', 'Reactivar'), ('IMPORTAR', 'Importar datos'), ('RESET_PASSWORD', 'Resetear contraseña'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('OTRO', 'Otro'), ('TRANSFERENCIA', 'Transferencia')], max_length=50),
        ),
        migrations.CreateModel(
            name='HistorialTransferenciaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transferencia', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('centro_costo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_destino', to='flota.centrocosto')),
                ('centro_costo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_origen', to='flota.centrocosto')),
                ('usuario_transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_vehiculos', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_transferencias', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Historial de transferencia de vehículo',
                'verbose_name_plural': 'Historial de transferencias de vehículos',
                'ordering': ['-fecha_transferencia', '-creado_en'],
            },
        ),
    ]
