# Generated by Django 6.0.5 on 2026-05-26 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0011_alter_bitacoraaccion_accion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MantencionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantencion', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('KILOMETRAJE', 'Por kilometraje'), ('SINIESTRO', 'Por siniestro')], max_length=30)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=30)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('kilometraje_programado', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('kilometraje_ingreso', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('kilometraje_cierre', models.PositiveIntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('observacion_cierre', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenciones_cerradas', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenciones', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Mantención de vehículo',
                'verbose_name_plural': 'Mantenciones de vehículos',
                'ordering': ['-fecha_programada', '-creado_en'],
            },
        ),
    ]
