# Generated by Django 6.0.5 on 2026-06-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0012_mantencionvehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocosto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
