# Generated by Django 4.2.22 on 2026-06-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0013_alter_bitacoraaccion_id_alter_centrocosto_id_and_more'),
        ('flota', '0013_centrocosto_activo'),
    ]

    operations = [
    ]
